<?php

/**
 * This is the model base class for the table "tbl_item_type".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ItemType".
 *
 * Columns in table "tbl_item_type" available as properties of the model,
 * followed by relations of table "tbl_item_type" available as properties of the model.
 *
 * @property integer $item_type_id
 * @property string $type
 *
 * @property Equipment[] $equipments
 */
abstract class BaseItemType extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_item_type';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ItemType|ItemTypes', $n);
	}

	public static function representingColumn() {
		return 'type';
	}

	public function rules() {
		return array(
			array('type', 'length', 'max'=>45),
			array('type', 'default', 'setOnEmpty' => true, 'value' => null),
			array('item_type_id, type', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'equipments' => array(self::HAS_MANY, 'Equipment', 'item_type_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'item_type_id' => Yii::t('app', 'Item Type'),
			'type' => Yii::t('app', 'Type'),
			'equipments' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('item_type_id', $this->item_type_id);
		$criteria->compare('type', $this->type, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}