<?php

/**
 * This is the model base class for the table "tbl_log".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Log".
 *
 * Columns in table "tbl_log" available as properties of the model,
 * followed by relations of table "tbl_log" available as properties of the model.
 *
 * @property integer $log_id
 * @property integer $item_number
 * @property integer $people_number
 * @property integer $reservation_number
 * @property string $log_time
 *
 * @property Equipment $itemNumber
 * @property People $peopleNumber
 * @property Reservation $reservationNumber
 */
abstract class BaseLog extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_log';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Log|Logs', $n);
	}

	public static function representingColumn() {
		return 'log_time';
	}

	public function rules() {
		return array(
			array('people_number', 'required'),
			array('item_number, people_number, reservation_number', 'numerical', 'integerOnly'=>true),
			array('log_time', 'safe'),
			array('item_number, reservation_number, log_time', 'default', 'setOnEmpty' => true, 'value' => null),
			array('log_id, item_number, people_number, reservation_number, log_time', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'itemNumber' => array(self::BELONGS_TO, 'Equipment', 'item_number'),
			'peopleNumber' => array(self::BELONGS_TO, 'People', 'people_number'),
			'reservationNumber' => array(self::BELONGS_TO, 'Reservation', 'reservation_number'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'log_id' => Yii::t('app', 'Log'),
			'item_number' => null,
			'people_number' => null,
			'reservation_number' => null,
			'log_time' => Yii::t('app', 'Log Time'),
			'itemNumber' => null,
			'peopleNumber' => null,
			'reservationNumber' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('log_id', $this->log_id);
		$criteria->compare('item_number', $this->item_number);
		$criteria->compare('people_number', $this->people_number);
		$criteria->compare('reservation_number', $this->reservation_number);
		$criteria->compare('log_time', $this->log_time, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}