<?php

/**
 * This is the model base class for the table "tbl_login".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Login".
 *
 * Columns in table "tbl_login" available as properties of the model,
 * followed by relations of table "tbl_login" available as properties of the model.
 *
 * @property integer $people_id
 * @property string $password
 *
 * @property People $people
 */
abstract class BaseLogin extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_login';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Login|Logins', $n);
	}

	public static function representingColumn() {
		return 'password';
	}

	public function rules() {
		return array(
			array('people_id', 'required'),
			array('people_id', 'numerical', 'integerOnly'=>true),
			array('password', 'length', 'max'=>255),
			array('password', 'default', 'setOnEmpty' => true, 'value' => null),
			array('people_id, password', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'people' => array(self::BELONGS_TO, 'People', 'people_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'people_id' => null,
			'password' => Yii::t('app', 'Password'),
			'people' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('people_id', $this->people_id);
		$criteria->compare('password', $this->password, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}