<?php

/**
 * This is the model base class for the table "tbl_reservation_equipment".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ReservationEquipment".
 *
 * Columns in table "tbl_reservation_equipment" available as properties of the model,
 * followed by relations of table "tbl_reservation_equipment" available as properties of the model.
 *
 * @property integer $item_number
 * @property integer $reservation_number
 *
 * @property Reservation $itemNumber
 * @property Equipment $reservationNumber
 */
abstract class BaseReservationEquipment extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_reservation_equipment';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ReservationEquipment|ReservationEquipments', $n);
	}

	public static function representingColumn() {
		return 'item_number';
	}

	public function rules() {
		return array(
			array('item_number, reservation_number', 'required'),
			array('item_number, reservation_number', 'numerical', 'integerOnly'=>true),
			array('item_number, reservation_number', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'itemNumber' => array(self::BELONGS_TO, 'Reservation', 'item_number'),
			'reservationNumber' => array(self::BELONGS_TO, 'Equipment', 'reservation_number'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'item_number' => null,
			'reservation_number' => null,
			'itemNumber' => null,
			'reservationNumber' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('item_number', $this->item_number);
		$criteria->compare('reservation_number', $this->reservation_number);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}