<?php

/**
 * This is the model base class for the table "tbl_equipment".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Equipment".
 *
 * Columns in table "tbl_equipment" available as properties of the model,
 * followed by relations of table "tbl_equipment" available as properties of the model.
 *
 * @property integer $item_number
 * @property string $su_number
 * @property string $manufacturer
 * @property string $model
 * @property string $accession_date
 * @property string $de_accession_date
 * @property integer $status_id
 * @property integer $item_type_id
 * @property string $serial_number
 * @property string $barcode_number
 * @property string $description
 *
 * @property EquipmentStatus $status
 * @property EquipmentType $itemType
 * @property Log[] $logs
 * @property ReservationItems[] $reservationItems
 */
abstract class BaseEquipment extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_equipment';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Equipment|Equipments', $n);
	}

	public static function representingColumn() {
		return 'su_number';
	}

	public function rules() {
		return array(
			array('status_id, item_type_id', 'required'),
			array('status_id, item_type_id', 'numerical', 'integerOnly'=>true),
			array('su_number, manufacturer, model, serial_number, barcode_number', 'length', 'max'=>45),
			array('description', 'length', 'max'=>255),
			array('accession_date, de_accession_date', 'safe'),
			array('su_number, manufacturer, model, accession_date, de_accession_date, serial_number, barcode_number, description', 'default', 'setOnEmpty' => true, 'value' => null),
			array('item_number, su_number, manufacturer, model, accession_date, de_accession_date, status_id, item_type_id, serial_number, barcode_number, description', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'status' => array(self::BELONGS_TO, 'EquipmentStatus', 'status_id'),
			'itemType' => array(self::BELONGS_TO, 'EquipmentType', 'item_type_id'),
			'logs' => array(self::HAS_MANY, 'Log', 'item_number'),
			'reservationItems' => array(self::HAS_MANY, 'ReservationItems', 'item_number'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'item_number' => Yii::t('app', 'Item Number'),
			'su_number' => Yii::t('app', 'Su Number'),
			'manufacturer' => Yii::t('app', 'Manufacturer'),
			'model' => Yii::t('app', 'Model'),
			'accession_date' => Yii::t('app', 'Accession Date'),
			'de_accession_date' => Yii::t('app', 'De Accession Date'),
			'status_id' => null,
			'item_type_id' => null,
			'serial_number' => Yii::t('app', 'Serial Number'),
			'barcode_number' => Yii::t('app', 'Barcode Number'),
			'description' => Yii::t('app', 'Description'),
			'status' => null,
			'itemType' => null,
			'logs' => null,
			'reservationItems' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('item_number', $this->item_number);
		$criteria->compare('su_number', $this->su_number, true);
		$criteria->compare('manufacturer', $this->manufacturer, true);
		$criteria->compare('model', $this->model, true);
		$criteria->compare('accession_date', $this->accession_date, true);
		$criteria->compare('de_accession_date', $this->de_accession_date, true);
		$criteria->compare('status_id', $this->status_id);
		$criteria->compare('item_type_id', $this->item_type_id);
		$criteria->compare('serial_number', $this->serial_number, true);
		$criteria->compare('barcode_number', $this->barcode_number, true);
		$criteria->compare('description', $this->description, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}