<?php

/**
 * This is the model base class for the table "tbl_reservation_status".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ReservationStatus".
 *
 * Columns in table "tbl_reservation_status" available as properties of the model,
 * followed by relations of table "tbl_reservation_status" available as properties of the model.
 *
 * @property integer $reservation_status_id
 * @property string $status
 *
 * @property Reservation[] $reservations
 */
abstract class BaseReservationStatus extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_reservation_status';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ReservationStatus|ReservationStatuses', $n);
	}

	public static function representingColumn() {
		return 'status';
	}

	public function rules() {
		return array(
			array('status', 'length', 'max'=>45),
			array('status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('reservation_status_id, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'reservations' => array(self::HAS_MANY, 'Reservation', 'reservation_status_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'reservation_status_id' => Yii::t('app', 'Reservation Status'),
			'status' => Yii::t('app', 'Status'),
			'reservations' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('reservation_status_id', $this->reservation_status_id);
		$criteria->compare('status', $this->status, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}