<?php

/**
 * This is the model base class for the table "tbl_person_role".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PersonRole".
 *
 * Columns in table "tbl_person_role" available as properties of the model,
 * followed by relations of table "tbl_person_role" available as properties of the model.
 *
 * @property integer $role_id
 * @property string $role
 *
 * @property People[] $peoples
 */
abstract class BasePersonRole extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_person_role';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PersonRole|PersonRoles', $n);
	}

	public static function representingColumn() {
		return 'role';
	}

	public function rules() {
		return array(
			array('role', 'length', 'max'=>45),
			array('role', 'default', 'setOnEmpty' => true, 'value' => null),
			array('role_id, role', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'peoples' => array(self::HAS_MANY, 'People', 'role_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'role_id' => Yii::t('app', 'Role'),
			'role' => Yii::t('app', 'Role'),
			'peoples' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('role_id', $this->role_id);
		$criteria->compare('role', $this->role, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}