<?php

/**
 * This is the model base class for the table "tbl_people".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "People".
 *
 * Columns in table "tbl_people" available as properties of the model,
 * followed by relations of table "tbl_people" available as properties of the model.
 *
 * @property integer $people_id
 * @property string $email_address
 * @property string $last_name
 * @property string $first_name
 * @property string $campus_phone
 * @property string $cell_phone
 * @property integer $role_id
 * @property string $student_id
 *
 * @property Log[] $logs
 * @property Login $login
 * @property PersonRole $role
 * @property Reservation[] $reservations
 * @property Reservation[] $reservations1
 */
abstract class BasePeople extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_people';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'People|Peoples', $n);
	}

	public static function representingColumn() {
		return 'email_address';
	}

	public function rules() {
		return array(
			array('role_id', 'required'),
			array('role_id', 'numerical', 'integerOnly'=>true),
			array('email_address, last_name, first_name, campus_phone, cell_phone, student_id', 'length', 'max'=>45),
			array('email_address, last_name, first_name, campus_phone, cell_phone, student_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('people_id, email_address, last_name, first_name, campus_phone, cell_phone, role_id, student_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'logs' => array(self::HAS_MANY, 'Log', 'people_number'),
			'login' => array(self::HAS_ONE, 'Login', 'people_id'),
			'role' => array(self::BELONGS_TO, 'PersonRole', 'role_id'),
			'reservations' => array(self::HAS_MANY, 'Reservation', 'people_id'),
			'reservations1' => array(self::HAS_MANY, 'Reservation', 'secondary_contact_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'people_id' => Yii::t('app', 'People'),
			'email_address' => Yii::t('app', 'Email Address'),
			'last_name' => Yii::t('app', 'Last Name'),
			'first_name' => Yii::t('app', 'First Name'),
			'campus_phone' => Yii::t('app', 'Campus Phone'),
			'cell_phone' => Yii::t('app', 'Cell Phone'),
			'role_id' => null,
			'student_id' => Yii::t('app', 'Student'),
			'logs' => null,
			'login' => null,
			'role' => null,
			'reservations' => null,
			'reservations1' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('people_id', $this->people_id);
		$criteria->compare('email_address', $this->email_address, true);
		$criteria->compare('last_name', $this->last_name, true);
		$criteria->compare('first_name', $this->first_name, true);
		$criteria->compare('campus_phone', $this->campus_phone, true);
		$criteria->compare('cell_phone', $this->cell_phone, true);
		$criteria->compare('role_id', $this->role_id);
		$criteria->compare('student_id', $this->student_id, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}